def build(bld):
  libs = ['modint', 'bit', 'rmq']

  for lib in libs:
    test_module = lib + '_test'
    source_file = test_module + '.cpp'
    bld.program(
      features = 'gtest',
      source = source_file,
      includes = '.',
      use = 'PTHREAD',
      target = test_module)

  libs2 = ['msp', 'edit_distance', 'kmp', 'unionfind']

  for lib in libs2:
    source_file_cpp = lib + '.cpp'
    source_file_hpp = lib + '.hpp'
    source_file_test = lib + '_test.cpp'
    test_module = lib + '_test'
    target_module = lib.upper();

    bld.stlib(
      source = source_file_cpp,
      includes = '.',
      use = 'PTHREAD',
      target = target_module)

    bld.program(
      features = 'gtest',
       source = source_file_test,
       includes = '.',
       use = ['PTHREAD', target_module],
       target = test_module)
